-- Generate Frida (Java) hook scripts for a class, a method, or a batch of search/usage results, and
-- drop them into a scratch JavaScript buffer ready to run with `frida -U -l <file>.js`.

local M = {}

local HEADER = [[
// Frida hooks generated by jadxnvim.
// Run:  frida -U -f <package> -l this.js --no-pause     (spawn)
//   or: frida -U -n <process> -l this.js                (attach)
// Note: class/method names are the app's *runtime* names. If you renamed a symbol
// in jadx, use its original name here (class ids already use the original names).
Java.perform(function () {
  function hook(clsName, methodName) {
    var cls;
    try { cls = Java.use(clsName); } catch (e) { console.log('[!] load ' + clsName + ': ' + e); return; }
    var m = cls[methodName];
    if (!m) { console.log('[!] no method ' + clsName + '.' + methodName); return; }
    m.overloads.forEach(function (ov) {
      ov.implementation = function () {
        var a = Array.prototype.slice.call(arguments);
        console.log('[+] ' + clsName + '.' + methodName + '(' + a.map(String).join(', ') + ')');
        var ret = ov.apply(this, arguments);
        console.log('    => ' + ret);
        return ret;
      };
    });
    console.log('[hooked] ' + clsName + '.' + methodName);
  }
  function hookClass(clsName) {
    var cls;
    try { cls = Java.use(clsName); } catch (e) { console.log('[!] load ' + clsName + ': ' + e); return; }
    var seen = {};
    cls.class.getDeclaredMethods().forEach(function (jm) {
      var n = jm.getName();
      if (seen[n]) return; seen[n] = true;
      hook(clsName, n);
    });
  }
]]

local FOOTER = "});\n"

local function jsstr(s)
  return "'" .. tostring(s or ""):gsub("\\", "\\\\"):gsub("'", "\\'") .. "'"
end

--- Build a Frida script from targets: a list of { class = "pkg.Cls", method = "name"|nil }.
--- A target with no method hooks every method of the class.
function M.script(targets)
  -- group by class, preserving first-seen order; whole-class overrides individual methods
  local order, by_class = {}, {}
  for _, t in ipairs(targets or {}) do
    local c = t and t.class
    if c and c ~= "" then
      if not by_class[c] then
        by_class[c] = { whole = false, methods = {}, morder = {} }
        order[#order + 1] = c
      end
      local e = by_class[c]
      if t.method and t.method ~= "" then
        if not e.methods[t.method] then
          e.methods[t.method] = true
          e.morder[#e.morder + 1] = t.method
        end
      else
        e.whole = true
      end
    end
  end
  local body = {}
  for _, c in ipairs(order) do
    local e = by_class[c]
    if e.whole then
      body[#body + 1] = "  hookClass(" .. jsstr(c) .. ");"
    else
      for _, m in ipairs(e.morder) do
        body[#body + 1] = "  hook(" .. jsstr(c) .. ", " .. jsstr(m) .. ");"
      end
    end
  end
  if #body == 0 then
    body[1] = "  // (no hookable targets)"
  end
  return HEADER .. table.concat(body, "\n") .. "\n" .. FOOTER
end

-- Derive hook targets from picker result items (class -> whole class, method -> that method,
-- everything else -> the containing class).
function M.from_items(items)
  local targets = {}
  for _, it in ipairs(items or {}) do
    if it.kind == "method" and it.id then
      targets[#targets + 1] = { class = it.id, method = it.rawName or it.name }
    elseif it.id then
      targets[#targets + 1] = { class = it.id } -- class / text / xref hit -> hook the class
    end
  end
  return targets
end

local counter = 0

--- Open a scratch JavaScript buffer containing the hook script for `targets`.
function M.open(targets, title)
  local script = M.script(targets)
  counter = counter + 1
  vim.cmd("botright vsplit")
  local buf = vim.api.nvim_create_buf(true, true)
  vim.api.nvim_win_set_buf(0, buf)
  pcall(vim.api.nvim_buf_set_name, buf, string.format("jadx-frida-%d-%s.js", counter, title or "hooks"))
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "hide"
  vim.bo[buf].swapfile = false
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(script, "\n", { plain = true }))
  vim.bo[buf].filetype = "javascript"
  vim.bo[buf].modified = false
  local n = 0
  for _ in pairs(targets or {}) do
    n = n + 1
  end
  vim.notify(string.format("[jadxnvim] generated Frida hooks for %d target(s) — :w to save the .js", n), vim.log.levels.INFO)
  return buf
end

return M
